baseURL = "https://example.org/"
languageCode = "it-IT"
title = "LanguageShop | Agenzia di traduzioni online"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "it"

# Site Params
[params]
logo = "images/logo.png"

# Languages managment settings: IT / EN 
[[Params.listeLangues]]
code = "it"
[[Params.listeLangues]]
code = "en"

# meta data
author = "Themefisher"
description = "This is meta description"

# Languages managment settings: IT / EN 
[Languages]
############ 1 - Sito in ITALIANO
[Languages.it]
weight = 1
languageCode = "it-it"
title = "LanguageShop - Agenzia di traduzioni online."
dateFormat = "2 Gennaio 2006"

home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "LanguageShop offre servizi di traduzioni, traduzioni giurate, interpretariato su decine di lingue diverse. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum nulla, soluta dolorum.."
footerServiceTitle = "Servizi"
footerQuicklinkTitle = "Link"
footerAboutTitle = "About"
footerSubscribeTitle = "Contattaci"

# Hero Area Section
[Languages.it.params.hero]
enable  = true
heading = "We love to make brands grow"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button  = true
btnText = "Leggi ancora"
#btnURL  = "https://themefisher.com/"
videoThumb = "images/slideOK.png"
imageCarousel1 = "images/slideOK.jpg"
imageCarousel2 = "images/slideOK2.jpg"
imageCarousel3 = "images/slideOK3.jpg"
#videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"


# About 2 Section
[Languages.it.params.aboutSm]
enable  = true
title   = "Ci occupiamo con passione delle vostre traduzioni da oltre dieci anni"
description = "Languageshop è un team di traduttori in grado di fornire traduzioni professionali che rispondono ai più elevati standard di qualità ed eseguite senza l’ausilio di tool automatici, a meno che non venga espressamente richiesto dal cliente. Perché amiamo mettere testa e cuore nelle nostre traduzioni."

# Blog Section On Homepage
[Languages.it.params.blog]
enable  = true
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.it.params.contact]
enable  = true
topTitle= "Mandatici una mail"
title   = "Contattaci."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "Pescara, Italia. Ma lavoriamo con tutto il mondo"
phone   = "000125429393+" 
facebook= "https://www.facebook.com/languageshop.it"
mapLatitude = "42.466359"
mapLongitude= "14.208652"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.it.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Contattaci"
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
btnText = "Contattaci"
btnURL  = "contact/" # TODO: change this in production.

############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "Example site multi-language"
dateFormat = "January 2, 2006"

home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "LanguageShop offre servizi di traduzioni, traduzioni giurate, interpretariato su decine di lingue diverse. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum nulla, soluta dolorum."
footerServiceTitle = "Servizi"
footerQuicklinkTitle = "Contattaci"
footerAboutTitle = "Chi siamo"

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "We love to make brands grow"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button  = true
btnText = "Know More"
#btnURL  = "https://themefisher.com/"
videoThumb = "images/slideOK.png"
#videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "We have explored the digital landscape with passion for a long time"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "Contact Us."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "Pescara, Italia. Ma lavoriamo con tutto il mondo"
phone   = "+393924521000"
facebook= "https://www.facebook.com/languageshop.it"
mapLatitude = "42.466359"
mapLongitude= "-0.127758"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Contattaci"
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
btnText = "Contattaci"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "listino"
url     = "pricing"
weight  = 4
[[menu.nav]]
name    = "blog"
url     = "blog"
weight  = 5
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 6

# Footer Service Menu
[[menu.service]]
name    = "graphicdesign"
url     = "service"
weight  = 1
[[menu.service]]
name    = "webdesign"
url     = "service"
weight  = 2
[[menu.service]]
name    = "webdevelopment"
url     = "service"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "partners"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 2
[[menu.quicklink]]
name    = "faqs"
url     = "about"
weight  = 3
[[menu.quicklink]]
name    = "badges"
url     = "about"
weight  = 4
